// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_og6Dkn_MIF_VbAMR6PM2CBC01kOSjVM',
    appId: '1:245753006863:web:24352e8f6dab4f2f8d0c7a',
    messagingSenderId: '245753006863',
    projectId: 'flash-chat-6ee35',
    authDomain: 'flash-chat-6ee35.firebaseapp.com',
    storageBucket: 'flash-chat-6ee35.appspot.com',
    measurementId: 'G-MFJSVX6QMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZnJXmMqtr-4xBg8jAex4ELL90gpYll-k',
    appId: '1:245753006863:android:9c9264d6858d50a68d0c7a',
    messagingSenderId: '245753006863',
    projectId: 'flash-chat-6ee35',
    storageBucket: 'flash-chat-6ee35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYwEosvKNK2nURNkxChpcmpuVN2CqGMuM',
    appId: '1:245753006863:ios:f4881dff2f1bbc238d0c7a',
    messagingSenderId: '245753006863',
    projectId: 'flash-chat-6ee35',
    storageBucket: 'flash-chat-6ee35.appspot.com',
    iosClientId: '245753006863-m7gcjvt01020a46ld4vtk6pelcs5ldfk.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYwEosvKNK2nURNkxChpcmpuVN2CqGMuM',
    appId: '1:245753006863:ios:932c5437ae91a04b8d0c7a',
    messagingSenderId: '245753006863',
    projectId: 'flash-chat-6ee35',
    storageBucket: 'flash-chat-6ee35.appspot.com',
    iosClientId: '245753006863-2ml86h89n7osqmju017f063v1ljfkbrj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChatApp.RunnerTests',
  );
}
